binance:
  websocket:
    base-url: wss://stream.binance.com:9443/stream
    trade-stream-suffix: "@trade"
    symbols:
      - btcusdt
  main:
    web-application-type: servlet

logging:
  level:
    com.coinflow: debug

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, health
  metrics:
    tags:
      application: coinflow-collector
