spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ohlc
    username: ohlc_user
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

redis:
  stream:
    tick:
      stream-key: tick:raw
      group: tick-consumer-group
      consumer-name: consumer-1

logging:
  level:
    org.hibernate.SQL: debug
