# Local development only

services:
  redis:
    image: redis:7.2
    container_name: redis-local
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        "--bind", "0.0.0.0",
        "--appendonly", "no",
        "--protected-mode", "no"
      ]
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter-local
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_EXPORTER_CHECK_STREAMS=tick:*
      - REDIS_EXPORTER_CHECK_KEYS=tick:*
    ports:
      - "9121:9121"
    depends_on:
      redis:
        condition: service_healthy
    restart: always
