# Local development for Spring Boot Apps ONLY
# Must be run after DB and Redis containers are up.

services:
  api-app:
    build:
      context: ../../backend/coinflow-api-app
      dockerfile: Dockerfile
    container_name: coinflow-api-local
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_NAME=application-api
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=host.docker.internal
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/ohlc
      - SPRING_DATASOURCE_USERNAME=ohlc_user
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-1234}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ws-gateway:
    build:
      context: ../../backend/coinflow-ws-gateway
      dockerfile: Dockerfile
    container_name: coinflow-ws-local
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_NAME=application-ws
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  consumer-app:
    build:
      context: ../../backend/coinflow-consumer-app
      dockerfile: Dockerfile
    container_name: coinflow-consumer-local
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_NAME=application-consumer
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=host.docker.internal
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/ohlc
      - SPRING_DATASOURCE_USERNAME=ohlc_user
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-1234}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  collector-app:
    build:
      context: ../../backend/coinflow-collector-app
      dockerfile: Dockerfile
    container_name: coinflow-collector-local
    ports:
      - "8083:8083"
    environment:
      - SPRING_CONFIG_NAME=application-collector
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - consumer-app
