plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':coinflow-common')
    implementation project(':coinflow-infra-redis')

    // WebFlux (Netty) for WebSocket
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    runtimeOnly "io.netty:netty-resolver-dns-native-macos:4.1.110.Final:osx-aarch_64"

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootJar { enabled = true }
jar { enabled = false }
