plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':coinflow-core')
    implementation project(':coinflow-common')
    implementation project(':coinflow-infra-redis')

    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.h2database:h2'
}

bootJar { enabled = true }
jar { enabled = false }
