spring:
  main:
    web-application-type: none
  application:
    name: replay-app
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ohlc}
    username: ${DB_USERNAME:ohlc_user}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always # Spring Batch Meta 테이블 자동 생성 속성 켜기

binance:
  api:
    base-url: "https://api.binance.com"

coinflow:
  batch:
    reconciliation:
      interval: 300000 # 5 minutes in milliseconds
      symbols:
        - "btcusdt"
      default-interval: "1m"
      window-minutes: 5
