global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'coinflow-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080' # API App
          - 'host.docker.internal:8081' # WS-Gateway
          - 'host.docker.internal:8082' # Consumer
          - 'host.docker.internal:8083' # Collector (Docker)

  - job_name: 'redis-server'
    static_configs:
      - targets: ['host.docker.internal:9121']
