plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':coinflow-core')
    implementation project(':coinflow-common')

    // redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // ConfigurationProperties metadata
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // cache
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'com.github.ben-manes.caffeine:caffeine'
}

bootJar { enabled = true }
jar { enabled = false }
