plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':coinflow-core')
    implementation project(':coinflow-common')
    implementation project(':coinflow-infra-redis')

    // JSON
    implementation 'org.springframework.boot:spring-boot-starter-json'

    // ConfigurationProperties metadata
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // WebSocket client (lightweight)
    implementation 'org.java-websocket:Java-WebSocket:1.5.4'
}

bootJar { enabled = true }
jar { enabled = false }
